#logging:
#  level:
#    com:
#      firstproject:
#        journalApp: INFO

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
